### ISSUE TITLE
Cannot load Loras, many models failing since latest BETA updates

### ISSUE THREAD

**Issue by 1010datacorder** [easydiffusion/easydiffusion#1444]
Many issues now loading models and loras. 

BETA update reset settings , had to go back into settings to re-activate BETA channel.

Since 29th July updates, loras and models failing including

SDXL VAE

**Comment by cmdr2** [comment]
@1010datacorder Can you please give a link to a lora that doesn't work for you? Which used to work for you previously.

I haven't heard any complaints about older loras, and just tested that they're still working. So please share a link to a lora that used to work, and we can take a look.

Thanks!

**Comment by 1010datacorder** [comment]
Hi, 

This appears to be largely fixed with either one of the later 29th or 30th of July updates.

SDXL VAEFIX now renders without errors. 

Pre SDXL models seem to be working now mostly with LORAS again. The main obvious problem was the "Add More Details" lora available on CIVITAI. These seems to be working.

I know we're early days with SDXL but I didn't notice any serious lag or anything using it so well done.

**Comment by iopenet** [comment]
Still fail to load some SD 1.5
Error: Could not load the lora model! Reason: Could not find text_encoder.text_model.encoder.layers

**Comment by Sub0X** [comment]
Same issue here as well when trying to load the illustrous stability Lora with several compatible SD models

```
'A:\\Models\\Images\\lora\\illustrious_best_quality_v1.safetensors',
'A:\\Models\\Images\\lora\\illustriousXLv01_stabilizer_v1.185c.safetensors'] to device: cuda:0
16:37:56.370 ERROR cuda:0 Could not find unet.down_blocks.1.attentions.0.proj_in.dora in the given  model_manager.py:187
object!
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\misc_utils.py", line 28,
in get_nested_attr
    curr_layer = curr_layer.__getattr__(temp_name)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line
1940, in __getattr__
    raise AttributeError(
AttributeError: 'Linear' object has no attribute 'dora'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 183, in
reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py",
line 54, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\lora.py",
line 72, in load_model
    loras =
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\lora.py",
line 72, in <listcomp>
    loras =
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\lora.py",
line 119, in load_lora
    raise e  # otherwise die
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\lora.py",
line 114, in load_lora
    block.module = get_nested_attr(pipe, block_name)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\misc_utils.py", line 35,
in get_nested_attr
    raise Exception(f"Could not find {key} in the given object!")
Exception: Could not find unet.down_blocks.1.attentions.0.proj_in.dora in the given object!
16:37:56.410 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:295
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 287, in thread_render
    task.run()
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 216, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the lora model! Reason: Could not find
unet.down_blocks.1.attentions.0.proj_in.dora in the given object!
```
