### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by Trantu1102** [easydiffusion/easydiffusion#1851]
**Describe the bug**
cannot import name 'cached_download' from 'huggingface_hub'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by vertikalm** [comment]
Same error with a fresh and clean Debian 12

**Comment by XDM-Inc** [comment]
same issue here, it looks like hugging face changed a lot of urls and i think thats what messed things up a bit. thats my educated guess because when i try go to the website its asking for it says 404 page not found

**Comment by orossant** [comment]
same issues on fresh install on Mac. the failed msg mention a folder and file that exist even if the path is a quite long string.

**Comment by Sru2003** [comment]
same issue here

**Comment by xezwary** [comment]
I removed cache_download from the import line in the file `/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py`
That fixed it for me

**Comment by XDM-Inc** [comment]
> I removed cached_download from the import line in the file `/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py` That fixed it for me

That I did the trick! 👍
Now I just got to figure out how to get my Radeon 7900 xtx on working and I'll be off to the races

**Comment by hudsonventura** [comment]
> I removed cached_download from the import line in the file `/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py` That fixed it for me

@xezwary, you tip works to me. Thanks.

**Comment by QueryType** [comment]
> same issues on fresh install on Mac. the failed msg mention a folder and file that exist even if the path is a quite long string : ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/Documents/MyTP/easy-diffusion/installer_files/env/lib/python3.8/sitepackages/huggingface_hub/**init**.py)

Same here. I applied the workaround and got an astronaut on a horse

**Comment by guangchen811** [comment]
This issue seems to arise from a breaking change in huggingface_hub version 0.26.0, where the cached_download() function has been fully removed. Downgrading to an earlier version of huggingface_hub should resolve this problem.

More details: https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0

**Comment by Bassaoud** [comment]
> **Describe the bug** cannot import name 'cached_download' from 'huggingface_hub'
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS:
> * Browser:
> * Version:
> 
> **Smartphone (please complete the following information):**
> 
> * Device:
> * OS:
> * Browser
> * Version
> 
> **Additional context** Add any other context about the problem here.

solution seems to here. While downgrading version i get this warning : 
*FutureWarning: 'cached_download' (from 'huggingface_hub.file_download') is deprecated and will be removed from version '0.26'. Use `hf_hub_download` instead.*

**Comment by thakral-kartik** [comment]
Downgrading from 0.26.1 to 0.20.2 worked for me.

**Comment by lauraaisling** [comment]
Likewise, downgrading to 0.25.0 seems to work, so it must be something with 0.26.

**Comment by Bassaoud** [comment]
SOLUTION : Replace **cached_download** by **hf_hub_download** in your **model.py**.

**Comment by VioletaChatalbasheva** [comment]
You could also update diffusers to the latest version which seems to be working without `cached_download `

**Comment by chunyu-li** [comment]
This is actually due to the breaking changes introduced in [diffusers 0.26.0](https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0).

<img width="883" alt="截屏2024-10-29 16 09 50" src="https://github.com/user-attachments/assets/bf43b7e1-d176-4cff-8790-c9250dd36cf9">

**Comment by fastdaima** [comment]
for me , downgrading the huggingface-hub version to `0.23.2` worked like a charm.

**Comment by LukeLIN-web** [comment]
> I removed cached_download from the import line in the file `/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py` That fixed it for me

Change lib seems not a good idea as it affect all other projects

**Comment by Alexander-RPR** [comment]
> SOLUTION : Replace **cached_download** by **hf_hub_download** in your **model.py**.

Specifically in which folder is the "model.py" file you mention located?

**Comment by edwrdcrpio** [comment]
> SOLUTION : Replace **cached_download** by **hf_hub_download** in your **model.py**.

Where do I locate model.py?

**Comment by cmdr2** [comment]
Sorry for the delay in fixing this, I've pushed a fix for this. It pins huggingface-hub to 0.23.2.

Please restart Easy Diffusion and try again, it should attempt to fix itself automatically.

Please let me know if that doesn't work, thanks!

**Comment by elielgvs** [comment]
> I removed cached_download from the import line in the file `/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py` That fixed it for me

Works perfectly here. Thanks

**Comment by edwrdcrpio** [comment]
Thanks all! I just deleted the cached_download from the import line

**Comment by ishandutta2007** [comment]
I downgraded huggingface_hub from 0.26.3 to 0.23.5 to resolve it
```
pip uninstall -y huggingface_hub
pip install huggingface_hub==0.23.5
```

**Comment by rainleon** [comment]
Maybe the package which refer huggingface_hub is needed to be updated,I fixed the same question by update diffusers  0.27.2 to 0.31.0.

**Comment by cmdr2** [comment]
@Undefinedefity  @rainleon @ishandutta2007 Sorry, but were you still facing this problem? Easy Diffusion already pins huggingface_hub to 0.21.4 (which shouldn't face this problem).

I pushed that fix nearly a month ago (Nov 15).

Since you've replied after the fix was pushed, I'm curious whether you're still facing this problem. Thanks!

**Comment by cmdr2** [comment]
Closing this, since it was fixed and I haven't heard back from anyone recently about this problem returning.

If it's still a problem for anyone, please let me know, and I'd be happy to reopen this issue.

**Comment by Wauplin** [comment]
Hey there, maintainer of `huggingface_hub` here. Sorry for all the trouble this breaking change introduced. The best 
 -and future proof- solution to fix this is to **upgrade `diffusers` version** to a more recent version (>=0.29.0).

```
pip install "diffusers>=0.29.0"
```

This fixed version dates back to June 2024. The issue with pinning `huggingface_hub` to an old version is that it might conflict with future versions of diffusers/transformers.

Hope this will prove useful :pray:

**Comment by DCharles01** [comment]
> Likewise, downgrading to 0.25.0 seems to work, so it must be something with 0.26.

This worked for me

**Comment by emosGambler** [comment]
For anyone lost here coming from ComfyUI, downgrade the huggingface_hub:
`pip install huggingface_hub==0.20.2`

**Comment by sdml0** [comment]
"pip install --upgrade diffusers" solved everything.

**Comment by shahzain110** [comment]
I removed cached_download from the import line in the file /easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py That fixed it for me

**Comment by Pied-Piper1** [comment]
Great!

**Comment by abhijit-innovxcare** [comment]
Use a monkey patch for cached_download function that was removed in newer versions of huggingface_hub.

`
"""
Patch for huggingface_hub compatibility with diffusers 0.28.0
This fixes the ImportError: cannot import name 'cached_download' from 'huggingface_hub'
"""

import sys
from typing import Optional, Union
from pathlib import Path

# Monkey patch for cached_download function that was removed in newer versions of huggingface_hub
def cached_download(
    url_or_filename: Union[str, Path],
    cache_dir: Optional[Union[str, Path]] = None,
    force_download: bool = False,
    proxies: Optional[dict] = None,
    resume_download: bool = False,
    user_agent: Optional[Union[str, dict]] = None,
    use_auth_token: Optional[Union[bool, str]] = None,
    local_files_only: bool = False,
    legacy_cache_layout: bool = False,
) -> str:
    """
    Legacy function that was removed from huggingface_hub.
    This is a compatibility wrapper that uses hf_hub_download instead.
    """
    from huggingface_hub import hf_hub_download
    
    # If it's a URL, we can't use hf_hub_download, so we'll use requests
    if str(url_or_filename).startswith(('http://', 'https://')):
        import requests
        import tempfile
        import os
        
        response = requests.get(url_or_filename, stream=True)
        response.raise_for_status()
        
        # Create a temporary file
        if cache_dir is None:
            cache_dir = os.path.expanduser("~/.cache/huggingface/hub")
        
        os.makedirs(cache_dir, exist_ok=True)
        filename = os.path.basename(url_or_filename)
        cache_path = os.path.join(cache_dir, filename)
        
        if not force_download and os.path.exists(cache_path):
            return cache_path
        
        with open(cache_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        
        return cache_path
    else:
        # For local files, just return the path
        return str(url_or_filename)

# Apply the monkey patch
def apply_patch():
    """Apply the monkey patch to huggingface_hub"""
    try:
        import huggingface_hub
        if not hasattr(huggingface_hub, 'cached_download'):
            huggingface_hub.cached_download = cached_download
            print("Applied huggingface_hub patch for cached_download")
    except ImportError:
        # If huggingface_hub hasn't been imported yet, we'll patch it when it's imported
        import builtins
        original_import = builtins.__import__
        
        def patched_import(name, *args, **kwargs):
            module = original_import(name, *args, **kwargs)
            if name == 'huggingface_hub' and not hasattr(module, 'cached_download'):
                module.cached_download = cached_download
                print("Applied huggingface_hub patch for cached_download")
            return module
        
        builtins.__import__ = patched_import

# Apply the patch immediately when this module is imported
apply_patch() 
`

This is very straight forward without messing up with the version of diffusers.

**Comment by Jaykumaran** [comment]
Downgrade huggingface_hub to 0.24
